import jsPDF from 'jspdf';
import type { Architecture } from '../types';

const PRIORITY_SYMBOL = { high: '●', medium: '◐', low: '○' } as const;
const SEVERITY_SYMBOL = { high: '▲', medium: '△', low: '▽' } as const;

export async function exportToPDF(arch: Architecture): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const PAGE_W = 210;
  const MARGIN = 18;
  const CONTENT_W = PAGE_W - MARGIN * 2;
  let y = MARGIN;

  // ── Helpers ──────────────────────────────────────────────
  const checkPage = (neededMM = 12) => {
    if (y + neededMM > 280) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const heading2 = (text: string) => {
    checkPage(12);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(50, 50, 80);
    doc.text(text, MARGIN, y);
    y += 7;
    // underline
    doc.setDrawColor(180, 160, 255);
    doc.setLineWidth(0.4);
    doc.line(MARGIN, y - 2, MARGIN + CONTENT_W, y - 2);
    y += 2;
  };

  const heading3 = (text: string, color: [number, number, number] = [60, 60, 90]) => {
    checkPage(10);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...color);
    doc.text(text, MARGIN, y);
    y += 6;
  };

  const body = (text: string, indent = 0) => {
    doc.setFontSize(9.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 70);
    const lines = doc.splitTextToSize(text, CONTENT_W - indent);
    lines.forEach((line: string) => {
      checkPage(5);
      doc.text(line, MARGIN + indent, y);
      y += 5;
    });
  };

  const pill = (text: string, x: number, yPos: number, bg: [number,number,number], fg: [number,number,number]) => {
    const pad = 2.5;
    doc.setFontSize(8);
    const tw = doc.getTextWidth(text);
    doc.setFillColor(...bg);
    doc.roundedRect(x, yPos - 3.5, tw + pad * 2, 5, 1, 1, 'F');
    doc.setTextColor(...fg);
    doc.text(text, x + pad, yPos);
    return tw + pad * 2 + 2;
  };

  const spacer = (mm = 4) => { y += mm; };

  // ── Cover ─────────────────────────────────────────────────
  doc.setFillColor(14, 10, 30);
  doc.rect(0, 0, PAGE_W, 60, 'F');
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(180, 150, 255);
  doc.text(arch.title, MARGIN, 28);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 140, 180);
  doc.text(`${arch.projectType}  ·  ${arch.scale}  ·  v${arch.version}`, MARGIN, 38);
  doc.setFontSize(8.5);
  doc.setTextColor(100, 90, 130);
  doc.text(`Generated by Architecture Mapper  ·  ${new Date().toLocaleDateString()}`, MARGIN, 47);

  y = 70;

  // ── Summary ───────────────────────────────────────────────
  heading2('Overview');
  body(arch.summary);
  spacer();

  // ── Layers ────────────────────────────────────────────────
  heading2('Architecture Layers');
  arch.layers.forEach((layer) => {
    checkPage(20);
    heading3(`${layer.icon}  ${layer.name}`);
    body(layer.description, 4);
    // Technologies
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 80, 180);
    doc.text('Stack:', MARGIN + 4, y);
    y += 4.5;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 100);
    body(layer.technologies.join('  ·  '), 4);
    // Features
    layer.features.forEach((f) => {
      checkPage(5);
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 100);
      doc.text(`• ${f}`, MARGIN + 6, y);
      y += 5;
    });
    spacer(3);
  });

  // ── Tech Stack ────────────────────────────────────────────
  heading2('Tech Stack');
  arch.techStack.forEach((item) => {
    checkPage(12);
    const catWidth = doc.getTextWidth(item.category) + 2;
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(120, 100, 200);
    doc.text(item.category, MARGIN, y);
    doc.setTextColor(30, 30, 50);
    doc.text(item.name, MARGIN + catWidth + 6, y);
    y += 5;
    body(item.reason, 4);
    spacer(2);
  });

  // ── Improvements ─────────────────────────────────────────
  heading2('Improvements');
  const PRIORITY_COLORS: Record<string, { bg: [number,number,number]; fg: [number,number,number] }> = {
    high: { bg: [80, 20, 20], fg: [255, 160, 160] },
    medium: { bg: [80, 60, 10], fg: [255, 210, 100] },
    low: { bg: [10, 60, 30], fg: [100, 220, 150] },
  };
  arch.improvements.forEach((imp) => {
    checkPage(14);
    const px = MARGIN;
    const col = PRIORITY_COLORS[imp.priority];
    pill(`${PRIORITY_SYMBOL[imp.priority]} ${imp.priority}`, px, y, col.bg, col.fg);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 50);
    doc.text(imp.title, px + 28, y);
    y += 6;
    body(imp.description, 4);
    spacer(2);
  });

  // ── Cost Estimate ─────────────────────────────────────────
  heading2('Cost Estimate');
  checkPage(20);
  doc.setFillColor(20, 14, 40);
  doc.roundedRect(MARGIN, y, CONTENT_W, 22, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(180, 150, 255);
  doc.text(`${arch.costEstimate.tier}`, MARGIN + 5, y + 7);
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text(
    `$${arch.costEstimate.monthlyMin} – $${arch.costEstimate.monthlyMax} / mo`,
    MARGIN + 5, y + 15
  );
  y += 26;
  body(arch.costEstimate.notes, 2);
  spacer();

  // ── Risk Analysis ─────────────────────────────────────────
  heading2('Risk Analysis');
  const SEV_COLORS: Record<string, { bg: [number,number,number]; fg: [number,number,number] }> = {
    high: { bg: [80, 20, 20], fg: [255, 160, 160] },
    medium: { bg: [80, 60, 10], fg: [255, 210, 100] },
    low: { bg: [10, 60, 30], fg: [100, 220, 150] },
  };
  arch.risks.forEach((risk) => {
    checkPage(14);
    const col = SEV_COLORS[risk.severity];
    pill(`${SEVERITY_SYMBOL[risk.severity]} ${risk.severity}`, MARGIN, y, col.bg, col.fg);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 50);
    doc.text(risk.title, MARGIN + 26, y);
    y += 6;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 100);
    body(`Mitigation: ${risk.mitigation}`, 4);
    spacer(2);
  });

  // ── Footer on each page ───────────────────────────────────
  const totalPages = (doc as jsPDF & { internal: { getNumberOfPages: () => number } })
    .internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(150, 140, 180);
    doc.text(
      `Architecture Mapper  ·  ${arch.title}  ·  Page ${i} of ${totalPages}`,
      MARGIN, 292
    );
  }

  doc.save(`${arch.title.replace(/\s+/g, '-').toLowerCase()}-v${arch.version}.pdf`);
}
