import type { Architecture } from '../types';

export function exportToMarkdown(arch: Architecture): void {
  const priorityEmoji = { high: '🔴', medium: '🟡', low: '🟢' };
  const severityEmoji = { high: '🔴', medium: '🟡', low: '🟢' };

  const md = `# ${arch.title}

> **Version ${arch.version}** · ${arch.projectType} · ${arch.scale}

## Overview

${arch.summary}

---

## Architecture Layers

${arch.layers
  .map(
    (layer) => `### ${layer.icon} ${layer.name}

${layer.description}

**Technologies:** ${layer.technologies.join(', ')}

**Features:**
${layer.features.map((f) => `- ${f}`).join('\n')}
`
  )
  .join('\n---\n\n')}

---

## Tech Stack

| Category | Technology | Rationale |
|----------|------------|-----------|
${arch.techStack.map((t) => `| ${t.category} | **${t.name}** | ${t.reason} |`).join('\n')}

---

## Improvements

${arch.improvements
  .map(
    (imp) =>
      `### ${priorityEmoji[imp.priority]} ${imp.title} (${imp.priority} priority)\n\n${imp.description}`
  )
  .join('\n\n')}

---

## Cost Estimate

**Tier:** ${arch.costEstimate.tier}  
**Monthly Range:** $${arch.costEstimate.monthlyMin} – $${arch.costEstimate.monthlyMax}  
**Notes:** ${arch.costEstimate.notes}

---

## Risk Analysis

${arch.risks
  .map(
    (r) =>
      `### ${severityEmoji[r.severity]} ${r.title} (${r.severity} severity)\n\n**Mitigation:** ${r.mitigation}`
  )
  .join('\n\n')}

---

*Generated by Architecture Mapper · ${new Date().toLocaleDateString()}*
`;

  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${arch.title.replace(/\s+/g, '-').toLowerCase()}-v${arch.version}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToJSON(arch: Architecture): void {
  const blob = new Blob([JSON.stringify(arch, null, 2)], {
    type: 'application/json',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${arch.title.replace(/\s+/g, '-').toLowerCase()}-v${arch.version}.json`;
  a.click();
  URL.revokeObjectURL(url);
}
